export enum websites {
    FEEDBURNER = 'https://feeds.feedburner.com/nigeriabitcoincommunity',
    BITCOINCHASER = 'https://bitcoinchaser.com/feed/',
    BITCOINIK = 'https://bitcoinik.com/feed/',
    BITCOINIST = 'https://bitcoinist.com/feed/',
    BITPINAS = 'https://bitpinas.com/feed/',
    BITCOINMARKETHOURNAL = 'https://www.bitcoinmarketjournal.com/feed/',
    TRUSTNODES = 'https://www.trustnodes.com/feed',
    BITCOINNEWS = 'https://bitcoinnews.com/feed/',
    COINIDOL = 'https://coinidol.com/rss2',
    COINCHECKUP = 'https://coincheckup.com/blog/feed',
    BITMEX_BLOG = 'https://blog.bitmex.com/feed',
    CRYPTOSLATE = 'https://cryptoslate.com/feed',
    BITFINEX_BLOG = 'https://blog.bitfinex.com/feed',
    BITCOIN_NEWS = 'https://news.bitcoin.com/feed',
    MEDIUM_COINMONKS = 'https://medium.com/feed/coinmonks',
    CRYPTOGENIUS = 'https://cryptogeni.us/feed',
    COINLABZ = 'https://coinlabz.com/feed',
    COINZENE = 'https://coinzene.com/feed',
    THECRYPTOTIME = 'https://thecryptotime.com/feed',
    FUNEXCLUB_BLOG = 'https://blog.funexclub.com/feed',
    COINBACKYARD = 'https://coinbackyard.com/feed',
    ALLINCRYPTO = 'https://allincrypto.com/feed',
    COINBOLD = 'https://coinbold.io/feed',
    SWAPS_BLOG = 'https://swaps.app/blog',
    BESTAICRYPTOCURRENCY = 'https://bestaicryptocurrency.com/feed',
    CRYPTOBRIEFING = 'https://cryptobriefing.com/feed',
    BITCOINMAGAZINE = 'https://bitcoinmagazine.com/.rss/full/',
    CRYPTOPOTATO = 'https://cryptopotato.com/feed/',
    COINSPEAKER_NEWS = 'https://www.coinspeaker.com/news/feed/',
    NEWSBTC = 'https://www.newsbtc.com/feed/',
    CRYPTODAILY = 'https://cryptodaily.co.uk/?utm_source=feedspot'

}   